version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    environment:
      - CONFIG_PATH=/config/prod.yaml
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - example
  db:
    image: postgres:15
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - example

networks:
  example:
    driver: bridge
