env: local # local/dev/prod
http_server:
  host: 0.0.0.0
  port: 8000
db:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  db_name: postgres
  sslmode:
grpc_server:
  host: 0.0.0.0
  port: 3000