env: dev # local/dev/prod
http_server:
  host: 0.0.0.0
  port: 8000
db:
  host: 213.226.127.82
  port: 5555
  user: urcop
  password: urcopka11_
  db_name: urcop
  sslmode:
grpc_server:
  host: 0.0.0.0
  port: 3000