name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.23.0

      - name: Build the Docker image
        run: docker build --build-arg CONFIG_PATH=/config/prod.yaml -t emotional_tracker_backend:latest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push the Docker image to Docker Hub
        run: docker tag emotional_tracker_backend:latest ${{ secrets.DOCKER_USERNAME }}/emotional_tracker_backend:latest
      - run: docker push ${{ secrets.DOCKER_USERNAME }}/emotional_tracker_backend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/emotional_tracker_backend:latest
            docker stop emotional_tracker_backend || true
            docker rm emotional_tracker_backend || true
            docker run -d --name emotional_tracker_backend -p 8001:8000 --restart unless-stopped ${{ secrets.DOCKER_USERNAME }}/emotional_tracker_backend:latest
